### ISSUE TITLE
Errore jinja2.exceptions.TemplateNotFound on  flask-argon-dashboard 

### ISSUE THREAD

**Issue by riddickskizzo** [app-generator/flask-argon-dashboard#4]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\Python37-32\FlaskApp\test\app\views.py", line 165, in index
    content=render_template( 'pages/404.html' ) )
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: pages/404.html

**Comment by app-generator** [comment]
Hello @riddickskizzo, 
Sorry for the delay and 10x for using this kit. The issue is solved. 

![github-flask-argon-404-err](https://user-images.githubusercontent.com/51070104/70369296-a4bea880-18bf-11ea-83f0-6038fa16e366.jpg)

**Comment by app-generator** [comment]
P.S. The enhanced version of this boilerplate that uses blueprints, dual config and other cool stuff:

[Flask Boilerplate Dashboard Argon](https://github.com/app-generator/flask-boilerplate-dashboard-argon) - MIT License. 

Cheers!

**Comment by app-generator** [comment]
App tested on Windows10 and Linux
